# Generated by Django 3.1.7 on 2021-05-28 00:20

from django.db import migrations, models
import graph.models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='image',
            field=models.ImageField(blank=True, upload_to=graph.models.Graph.upload_path),
        ),
    ]
