# Generated by Django 3.2.3 on 2021-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_graph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
