# Generated by Django 3.1.7 on 2021-05-02 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210428_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
