# Generated by Django 3.2.3 on 2021-06-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userfile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='content_type',
        ),
    ]
